---
title: "My Website"
author: "Molly Zaleski"
date: "November 29, 2017"
output: html_document
editor_options: 
  chunk_output_type: inline
---
###Bringing in the data:
```{r, cache=TRUE}
escapement <- read.csv("knb.92020.1.csv", stringsAsFactors = FALSE)
```

```{r, echo=FALSE}
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(leaflet)
  library(ggplot2)
  library(DT)
  })
```

###Calculating the median annual escapement by species
```{r}
med.escapament <- escapement %>%
  separate(sampleDate, c("Year","Month","Day"), sep = "-") %>%
  group_by(Species, Location, Year) %>%
  summarize(escapement = sum(DailyCount, na.rm = TRUE)) %>% #na.rm removes all NA's, just in case
  group_by(Species) %>%
  summarize(Median_Escapement = median(escapement))
```

```{r}
ggplot(med.escapament, aes(Species, Median_Escapement)) +
  geom_col() +
  coord_flip()
```

###Plotting the individual sampling locations
```{r}
locations <- escapement %>%
  distinct(Location, Latitude, Longitude) %>%
  drop_na()

leaflet(locations) %>%
  addTiles() %>% #can recreate Google Maps within the document
  addMarkers(~ -abs(Longitude), ~ Latitude, popup = ~ Location) #-abs(Long) because some lat/long were showing in RUssia

```

Ooh^ooh^
